name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[FEATURE] '
labels: ['enhancement', 'feature-request']
assignees: ['amitdubeyup']

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! ✨

  - type: textarea
    id: feature-description
    attributes:
      label: ✨ Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve?
      placeholder: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions you've considered.
      placeholder: What alternatives have you considered?

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocks current work
        - Critical - Essential for project
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: ⚙️ Implementation Complexity
      description: How complex do you think this feature is to implement?
      options:
        - Simple - Small change or addition
        - Medium - Moderate effort required
        - Complex - Significant development work
        - Major - Large architectural changes

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: What should be true when this feature is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, mockups, or examples.
      placeholder: Screenshots, mockups, related issues, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature aligns with the project goals
          required: true
        - label: I would be willing to help implement this feature
          required: false
